---
# Run this playbook first to create openvpn server and CA on the single machine

- hosts: all
  become: true
  tasks:
    - import_tasks: tasks/server_preparation.tasks.yml
    - import_tasks: tasks/server_net.tasks.yml
    - import_tasks: tasks/ca_pki.tasks.yml
    - import_tasks: tasks/server_pki.tasks.yml
    - import_tasks: tasks/server_registration.tasks.yml
    - import_tasks: tasks/server_gathering_files.tasks.yml
    - import_tasks: tasks/server_daemons.tasks.yml
    - import_tasks: tasks/server_client_infrastructure.tasks.yml

...