---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # Easy RSA vars
    easy_rsa_origin_directory: /easy_rsa_origin
    easy_rsa_origin_file: "{{ easy_rsa_origin_directory }}/master.zip"

    # Base vars
    openvpn_root_path: /openvpn
    openvpn_ca_path: "{{ openvpn_root_path }}/ca"
    openvpn_server_path: "{{ openvpn_root_path }}/server"
    openvpn_daemon_path:  /etc/openvpn

    openvpn_ca_easyrsa_path: "{{ openvpn_ca_path }}/easy-rsa-master/easyrsa3"
    openvpn_server_easyrsa_path: "{{ openvpn_server_path }}/easy-rsa-master/easyrsa3"

    openvpn_ca_pki_path: "{{ openvpn_ca_easyrsa_path }}/pki"
    openvpn_server_pki_path: "{{ openvpn_server_easyrsa_path }}/pki"

    # Certification authority vars
    openvpn_ca_certificate_file_path: "{{ openvpn_ca_pki_path }}/ca.crt"
    openvpn_ca_crl_file_path: "{{ openvpn_ca_pki_path }}/crl.pem"

    # Server vars
    openvpn_server_name: vpn-server
    openvpn_server_request_file_path: "{{ openvpn_server_pki_path }}/reqs/server.req"
    openvpn_server_signed_sertificate_file_path: "{{ openvpn_ca_pki_path }}/issued/vpn-server.crt"
    openvpn_server_diffie_hellman_file_path: "{{ openvpn_server_pki_path }}/dh.pem"
    openvpn_server_private_key_file_path: "{{ openvpn_server_pki_path }}/private/server.key"

    ta_key_file: "{{ openvpn_daemon_path }}/ta.key"

    # Client infrastructure vars
    client_infrastructure_path: "{{ openvpn_root_path }}/client-configs"
    client_keys_path: "{{ client_infrastructure_path }}/keys"
    client_files_path: "{{ client_infrastructure_path }}/files"
    make_config_script: "{{ client_infrastructure_path }}/make_config.sh"
    client_name: client1

    # New client vars
    new_client_request: "{{ openvpn_server_pki_path }}/reqs/{{ client_name }}.req"
    new_client_key: "{{ openvpn_server_pki_path }}/private/{{ client_name }}.key"
    new_client_cert: "{{ openvpn_ca_pki_path }}/issued/{{ client_name }}.crt"
    new_client_config_file: "{{ client_files_path }}/{{ client_name }}.ovpn"

  hosts:
    104.197.188.144
