---

- name: Install required packages
  apt:
    pkg:
      - zip
      - openvpn

- name: Create openssl.cnf file
  template:
    src: templates/openssl.cnf.j2
    dest:  /etc/openvpn/openssl.cnf
    mode: '0755'

- name: Create server.conf file
  template:
    src: templates/server.conf.j2
    dest:  /etc/openvpn/server.conf
    mode: '0755'

...