---

- name: Generate static HMAC key
  shell:
    cmd: "openvpn --genkey --secret ta.key"
    chdir: "{{ openvpn_daemon_path }}"

- name: Copy CA certificate
  shell:
    cmd: "cp {{ openvpn_ca_certificate_file_path }} {{ openvpn_daemon_path }}"

- name: Copy CA CRL
  shell:
    cmd: "cp {{ openvpn_ca_crl_file_path }} {{ openvpn_daemon_path }}"

- name: Copy OpenVPN server certificate
  shell:
    cmd: "cp {{ openvpn_server_signed_sertificate_file_path }} {{ openvpn_daemon_path }}"

- name: Copy OpenVPN server private key
  shell:
    cmd: "cp {{ openvpn_server_private_key_file_path }} {{ openvpn_daemon_path }}"

- name: Copy Diffie-Hellman file
  shell:
    cmd: "cp {{ openvpn_server_diffie_hellman_file_path }} {{ openvpn_daemon_path }}"



...