---

- name: Revoke cert by client name
  shell:
    cmd: "./easyrsa revoke {{ client_name }}"
    chdir: "{{ openvpn_ca_easyrsa_path }}"
  environment:
    EASYRSA_BATCH: 1

- name: Generate new crl.pem
  shell:
    cmd: "./easyrsa gen-crl"
    chdir: "{{ openvpn_ca_easyrsa_path }}"

- name: Copy new crl.pem to daemon path
  shell:
    cmd: "cp {{ openvpn_ca_crl_file_path }} {{ openvpn_daemon_path }}"

- name: Restart openvpn server
  systemd:
    enabled: yes
    state: restarted
    name: openvpn@server

...