---

- name: Server - Create openVPN server directory
  file:
    path: "{{ openvpn_server_path }}"
    state: directory
    mode: 0755

- name: Server - unarchive easy-rsa
  unarchive:
    src: "{{ easy_rsa_origin_file }}"
    dest: "{{ openvpn_server_path }}"
    remote_src: yes

- name: Server - Check is Publick Key Infrastructure (PKI) exist
  stat:
    path: "{{ openvpn_server_pki_path }}"
  register: pki_folder

- name: Server - Create publick keys infrastructure
  shell:
    cmd: "./easyrsa init-pki"
    chdir: "{{ openvpn_server_easyrsa_path }}"
  when: pki_folder.stat.isdir is not defined

- name: Server - Check is cert request already created
  stat:
    path: "{{ openvpn_server_request_file_path }}"
  register: server_request

- name: Server - Create cert request and private key
  shell:
    cmd: "./easyrsa gen-req server nopass"
    chdir: "{{ openvpn_server_easyrsa_path }}"
  environment:
    EASYRSA_BATCH: 1
  when: server_request.stat.isdir is not defined

- name: Server - Check is Diffie-Hellman file already exist
  stat:
    path: "{{ openvpn_server_diffie_hellman_file_path }}"
  register: diffie_hellman

- name: Server - Diffie-Hellman file
  shell:
    cmd: "./easyrsa gen-dh"
    chdir: "{{ openvpn_server_easyrsa_path }}"
  environment:
    EASYRSA_BATCH: 1
  when: diffie_hellman.stat.isreg is not defined

...